apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: replicas.yaml # Of patch.yaml, zolang het bestand maar bestaat

configMapGenerator:
  - name: mykustom-map
    envs:               # Let op: 'envs' (meervoud) is vaak beter voor .properties
      - config.properties


#bases:
#- ../../base

#patches:
# - replicas.yaml

#configMapGenerator:
#- name: mykustom-map
#  env: config.properties
